### PR TITLE
bug fix: Now changing playback speed of ofxSoundPlayerObject works fine.

### PR DESCRIPTION
**Pull request by sadmb**
As "example-soundPlayerObject" didn't work fine with changing playback speed, I've debugged ofxSoundPlayerObject class.

### CODE REVIEW

**Comment by roymacdonald** [comment]
Thanks for your PR. There is a nasty bug in openFrameworks' ofSoundBuffer related to resampling audio, which affects changing speed. Because of that I implemented [ofxSampleRate](https://github.com/roymacdonald/ofxSampleRate) to deal with resampling using libsamplerate. With it it works well and the code works properly, thus I am hesitant to merge your PR.
What was that you were trying to fix?

**Comment by sadmb** [comment]
Actually it was very simple.
I checked waveform of ofSoundBuffer resampling with changing speed without ofxSoundPlayerObject and it looks fine.
Also checked the behavior of bug carefully and it seems the speed was changed exponentially.
Then I checked the process of changing position of instance, there it was.


```
i.position += nFrames;
				if(i.bUsePreprocessedBuffer){
					nf = i.preprocessedBuffer.getNumFrames();
				}else{
					i.position *=i.relativeSpeed;
				}
				 

```


position should be updated as `i.position += i.relativeSpeed * nFrames` but it was added `nFrames` then multiplied by `relativeSpeed`.

**Comment by sadmb** [comment]
Actually when you compare with ofFmodSoundPlayer, it sounds more noisy with resampling by ofSoundBuffer. Maybe there are better algorithms for resampling audio data with changing speed.
I’ll try ofxSampleRate too later. Thanks!

**Comment by roymacdonald** [comment]
thanks for explaining. You are right. It might be that the speed is not changing linearly.
Will double check to merge your PR.
I have not compiled ofxSampleRate for all platforms but it is quite straight forwards for whichever you use.
Currently I only have it compiled for Macos.
If you get ofxSampleRate running you then just need to use Project Generator  to add it to the project where you use ofxSoundObjects. Nothing else needed to be done.

**Comment by roymacdonald** [comment]
you are right. I actually been using the experimental branch as my default for ofxSoundObjects and in it, it is implemented as you mention here. 

Merging your PR.

I will probably make the experimental branch the master as well

**Pull request merged**
